spring.profiles.active=prod
db.schema=weather
cookie.duration=7200
cookie.name=sessionId
session.duration=7200000
weather.api.url=https://api.openweathermap.org/
weather.api.key=key
weather.api.units=metric
weather.api.language=ru
weather.api.limit=10